version: "3"
services:
  server:
    build: ./server
    expose:
      - 1234
    environment:
      API_HOST: 3000
      API_SERVER_PORT: 1234
    ports:
      - 1234:1234
    volumes:
      - ./server/src:/srv/app/jobcoin-admin-server/src
    command: npm run server
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/srv/app/jobcoin-admin-client/src
      - ./client/public:/srv/app/jobcoin-admin-client/public
    links:
      - server
    command: npm run client
